[global]
pid = /tmp/opcache_user_cache_benchmark.php-fpm.pid
error_log = /tmp/opcache_user_cache_benchmark.php-fpm.log
daemonize = no

[www]
listen = 127.0.0.1:9000
pm = static
pm.max_children = 5
pm.max_requests = 0
clear_env = no
catch_workers_output = yes
decorate_workers_output = no
user = www-data
group = www-data
